########Maven##########
#There are build systems for different languages:
$ C++: make, cmake, premake
$ Java: ant+, maven, gradle
$ C#: msbuild
##maven release type
1. Release
2. Snapshot

# 3 build lifecycle in maven? What does mvn site does?
1.clean
pre-clean	execute processes needed prior to the actual project cleaning
clean	    remove all files generated by the previous build
post-clean  execute processes needed to finalize the project cleaning
2.build
validate - validate the project is correct and all necessary information is available
compile -  compile the source code of the project
test -     test the compiled source code using a suitable unit testing framework. These tests should not require the code be packaged or deployed
package -  take the compiled code and package it in its distributable format, such as a JAR.
verify -   run any checks on results of integration tests to ensure quality criteria are met
install -  install the package into the local repository, for use as a dependency in other projects locally
deploy -   done in the build environment, copies the final package to the remote repository for sharing with other developers and projects.
3.site
pre-site	execute processes needed prior to the actual project site generation
site	    generate the projects site documentation
post-site	execute processes needed to finalize the site generation, and to prepare for site deployment
site-deploy	deploy the generated site documentation to the specified web server
##########Difference between mvn install and mvn deploy
mvn install
mvn deploy
============================================================================================================
mvn -> pom.xml
	    1.DOWNLOAD A PACKAGE > setting.xml (mirror)
	    2.UPLOAD A PACK ----> pom.xml (distributionManagement)
mvn install
compile test -> package -> copy to Local repo(.m2)     vs  copy from Local repo to remote repo(pom.xml)
        		    ----------------------         ---------------------------------------------
			    install                         deploy
============================================================================================================

It generate project report which will inculde project summary, project license, dependency, source repositories, continue integration report, and html document.
###To create a maven project
$ mvn archetype:generate
$ mvn archetype:generate  -DarchetypeArtifactIds=maven-archetype-webapp -DgroupId=com.ikt -DartifactId=project-ikt -Dversion=1.0 -Dpackage=com.ikt.project-ikt  -Dinteractivemode=false
########add dependency in pom.xml(project object model)
##under dependencies in pom.xml
 
 <dependencies>
  	<dependency>
  		<groupId>org.seleniumhq.selenium</groupId>
  		<artifactId>selenium-java</artifactId>
  		<version>3.141.59</version>
  	</dependency>
  	<dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>
  </dependencies>

####adding nexus in pom.xml
Deployment to a repository is configured in the pom.xml for the respective project in the distributionManagement section. Using the default repositories of the repository manager:

<project>
...
<distributionManagement>
    <repository>
      <id>nexus</id>
      <name>Releases</name>
      <url>http://localhost:8081/repository/maven-releases</url>
    </repository>
    <snapshotRepository>
      <id>nexus</id>
      <name>Snapshot</name>
      <url>http://localhost:8081/repository/maven-snapshots</url>
    </snapshotRepository>
  </distributionManagement>
...
 
#################
 $ vim pom.xml
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>16</release>
        </configuration>
      </plugin>
    </plugins>
    
  </build>
  <dependencies>
  	<dependency>
  		<groupId>org.seleniumhq.selenium</groupId>
  		<artifactId>selenium-java</artifactId>
  		<version>3.141.59</version>
  	</dependency>
  	
	<!-- https://mvnrepository.com/artifact/junit/junit -->
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.13.2</version>
		<scope>test</scope>
	</dependency>

	<dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>
  </dependencies>
</project>
:wq

##############maven interview questions##
1.what is multi module project in maven and what are the setting you want to do in multi module parent and child project? what is dependency management?
A:
https://www.baeldung.com/maven-multi-module
2.what is transitive dependency?
3.when i issue mvn install what all things happen in background?
4.what are the settings you need to do before running mvn deploy?
5.why maven takes much time for 1st execution and from 2nd execution it will take less time?
6.m2 is local repository for maven, now I don’t want to use .m2 folder as my local repository I want to use some other folder as my local, is it possible in maven? If yes, how would you do that?
mvn install -Dmaven.repo.local=/alternate/repo/location 
7.What are things you need to set, if you want download dependency from private repository ?
8.What are the issues you faced while working on maven projects?
9.Command to skip the test cases in maven
$ sh "mvn package -DskipTests"
10.what is multi module project?
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-java</artifactId>
<version>3.141.59</version>
11.what is the importance of dependency managment?
12.what are the settings that you need to do for mvn deploy ( to push artifcats to repository )?
13.mvn version that you have used?
14.Tell me 3 build lifecycle in maven? What does mvn site does?
1.clean
pre-clean	execute processes needed prior to the actual project cleaning
clean	    remove all files generated by the previous build
post-clean  execute processes needed to finalize the project cleaning
2.build
validate - validate the project is correct and all necessary information is available
compile -  compile the source code of the project
test -     test the compiled source code using a suitable unit testing framework. These tests should not require the code be packaged or deployed
package -  take the compiled code and package it in its distributable format, such as a JAR.
verify -   run any checks on results of integration tests to ensure quality criteria are met
install -  install the package into the local repository, for use as a dependency in other projects locally
deploy -   done in the build environment, copies the final package to the remote repository for sharing with other developers and projects.
3.site
pre-site	execute processes needed prior to the actual project site generation
site	generate the projects site documentation
post-site	execute processes needed to finalize the site generation, and to prepare for site deployment
site-deploy	deploy the generated site documentation to the specified web server

It generate project report which will inculde project summary, project license, dependency, source repositories, continue integration report, and html document.

15.Is there way by which we can set local repository as some other custom directory, other than .m2?
16.Settings that you make for mvn deploy?
we need define repository that we   deploy in project pom.xml file in <distributionManagement>  section we need define Id name and url of repository of the deploy.
  <distributionManagement>
    <repository>
      <id>internal.repo</id>
      <name>MyCo Internal Repository</name>
      <url>Host to Company Repository</url>
    </repository>
  </distributionManagement>
and aslo we need  define authenication information in setting.xml
 <server>
      <id>internal.repo</id>
      <username>maven</username>
      <password>foobar</password>
    </server>
17.What is the default value of packaging tag? What other values for other artifact types?
18.What are GAVs?
groupId
artifactId
version
we use to unqinelly identify our project
19.what are the tags that you came across in pom.xml?
20.Explain maven life cycle?
